BackEnd/controllers/task.js, BackEnd/model/Task.js, BackEnd/model/export/Exporter.js, BackEnd/model/tasks/AnonTask.js, BackEnd/model/tasks/DeleteTask.js, BackEnd/model/tasks/ExportTask.js, BackEnd/model/tasks/RetrieveTask.js, BackEnd/routes/admin.js, FrontEnd/src/assets/styles/orthancToolsJs.css, FrontEnd/src/components/Admin/AdminRootPanel.js, FrontEnd/src/components/Admin/Robots/TaksFlushPanel.js, FrontEnd/src/components/Admin/Robots/TaskRootPanel.js, FrontEnd/src/services/anon.js, FrontEnd/src/services/deleteRobot.js, FrontEnd/src/services/exportDicom.js, FrontEnd/src/services/retrieveRobot.js
Adding a way to flush bull queues
=> Feature flush bull

BackEnd/model/tasks/AnonTask.js, BackEnd/model/tasks/DeleteTask.js, BackEnd/model/tasks/ExportTask.js, BackEnd/model/tasks/RetrieveTask.js, FrontEnd/src/components/Admin/Robots/RobotStatus.js, FrontEnd/src/components/Anonymize/AnonymizePanelProgress.js, FrontEnd/src/components/AutoQuery/Connected_Component/RobotView.js
=> WIP : Refac api

BackEnd/controllers/options.js, BackEnd/controllers/task.js, BackEnd/database/migrations/20200201140939-create-Options.js, BackEnd/database/models/option.js, BackEnd/model/Options.js, BackEnd/routes/admin.js, FrontEnd/src/components/Admin/Endpoints/EndpointsOptions.js, FrontEnd/src/components/Admin/Endpoints/EndpointsRootPanel.js, FrontEnd/src/services/options.js
Add a transcoding option for export to external
=> Feature transcoding export

BackEnd/.env, BackEnd/controllers/role.js, BackEnd/controllers/task.js, BackEnd/model/OrthancQueue.js, BackEnd/model/Task.js, BackEnd/model/tasks/AnonTask.js, BackEnd/model/tasks/DeleteTask.js, BackEnd/model/tasks/ExportTask.js, BackEnd/model/tasks/RetrieveTask.js, BackEnd/routes/admin.js, BackEnd/routes/index.js, FrontEnd/src/assets/styles/orthancToolsJs.css, FrontEnd/src/components/Admin/Robots/RobotStatus.js, FrontEnd/src/components/Anonymize/AnonHistoric.js, FrontEnd/src/components/Anonymize/AnonRootPanel.js, FrontEnd/src/components/Anonymize/AnonymizePanelProgress.js, FrontEnd/src/components/Anonymize/AnonymizedResults.js, FrontEnd/src/components/AutoQuery/Connected_Component/AutoQueryRoot.js, FrontEnd/src/components/AutoQuery/Connected_Component/CreateRobot.js, FrontEnd/src/components/AutoQuery/Connected_Component/Results.js, FrontEnd/src/components/AutoQuery/Connected_Component/RobotHistoric.js, FrontEnd/src/components/AutoQuery/Connected_Component/RobotView.js, FrontEnd/src/components/Main/NavBar.js, FrontEnd/src/services/retrieveRobot.js
Ajout d'un historique pour les taches de retrieve et d'anonymisation
=> Feature retrieve historic

BackEnd/adapter/bullAdapter.js
=> Fix issue 536

FrontEnd/src/assets/styles/orthancToolsJs.css, FrontEnd/src/components/Anonymize/AnonHistoric.js, FrontEnd/src/components/Anonymize/AnonRootPanel.js, FrontEnd/src/components/Anonymize/AnonymizedResults.js
=> Feature historique modal

FrontEnd/src/components/OrthancContent/LabelDropdown.js
=> Making label assignation progressive

BackEnd/adapter/basicFtpAdapter.js, BackEnd/adapter/bullAdapter.js, BackEnd/adapter/ssh2SftpClientAdapter.js, BackEnd/adapter/webdavAdapter.js, BackEnd/model/export/Endpoint.js, BackEnd/model/tasks/ExportTask.js, FrontEnd/src/components/Export/SendExternalDropdown.js, FrontEnd/src/tools/MonitorTask.js
Closes #555 
Adds error handling in the export tasks
=> Fix issue 555

BackEnd/adapter/bullAdapter.js
=> Removing batching in bull adapter

BackEnd/.env, FrontEnd/src/components/AutoQuery/Connected_Component/AutoQueryRoot.js, FrontEnd/src/components/AutoQuery/Connected_Component/RobotView.js, FrontEnd/src/components/AutoQuery/Connected_Component/TableQuery.js, FrontEnd/src/components/AutoQuery/Connected_Component/TableResultStudy.js, FrontEnd/src/components/AutoQuery/Connected_Component/TableResultsStudiesSeries.js, FrontEnd/src/components/CommonComponents/RessourcesDisplay/ReactTable/ColumnFactories.js, FrontEnd/src/components/CommonComponents/RessourcesDisplay/ReactTable/ColumnFilters.js, FrontEnd/src/components/CommonComponents/RessourcesDisplay/ReactTable/CommonSelectingSortingFilteringTable.js, FrontEnd/src/components/CommonComponents/RessourcesDisplay/ReactTable/CommonTable.js, FrontEnd/src/components/CommonComponents/RessourcesDisplay/ReactTable/NestedTable.js, FrontEnd/src/components/CommonComponents/RessourcesDisplay/ReactTable/RobotTable.js, FrontEnd/src/components/CommonComponents/RessourcesDisplay/ReactTable/TablePatients.js, FrontEnd/src/components/CommonComponents/RessourcesDisplay/ReactTable/TablePatientsWithNestedStudies.js, FrontEnd/src/components/CommonComponents/RessourcesDisplay/ReactTable/TablePatientsWithNestedStudiesAndSeries.js, FrontEnd/src/components/CommonComponents/RessourcesDisplay/ReactTable/TableSeries.js, FrontEnd/src/components/CommonComponents/RessourcesDisplay/ReactTable/TableStudiesWithNestedSeries.js, FrontEnd/src/components/CommonComponents/RessourcesDisplay/ReactTable/TableStudy.js, FrontEnd/src/components/Main/NavBar.js, FrontEnd/src/components/OrthancContent/ContentRootPanel.js, FrontEnd/src/components/Query/Connected_Components/TableResultStudy.js
Fix de bugs diverses liés à la migration vers react table
=> Fix react table

BackEnd/.env, BackEnd/model/tasks/AnonTask.js, FrontEnd/src/components/Import/CreateDicom.js
Adds popup for successful dicom creation
Define required tags
closes #646 closes #645
=> Tweaks create dicoms

FrontEnd/src/components/Anonymize/AnonymizePanel.js
=> changed the Columns of the patient and study table

FrontEnd/src/components/CommonComponents/RessourcesDisplay/ReactTable/ColumnFactories.js
=> Remove now remove rather than delete

FrontEnd/src/components/AutoQuery/Connected_Component/TableQuery.js, FrontEnd/src/components/CommonComponents/RessourcesDisplay/ReactTable/EditableCells.js
=> Adding a select for modalities to the autoquery table

BackEnd/model/export/Exporter.js, BackEnd/model/tasks/ExportTask.js, FrontEnd/src/assets/styles/orthancToolsJs.scss, FrontEnd/src/components/Export/SendExternalDropdown.js, FrontEnd/src/tools/MonitorTask.js
=> Feature export file name

FrontEnd/src/components/AutoQuery/Connected_Component/TableQuery.js, FrontEnd/src/components/CommonComponents/RessourcesDisplay/ReactTable/CommonSelectingAndFilteringTable.js, FrontEnd/src/components/CommonComponents/RessourcesDisplay/ReactTable/CommonSelectingSortingFilteringTable.js, FrontEnd/src/components/CommonComponents/RessourcesDisplay/ReactTable/RobotTable.js
- closes #658
- closes #661 
- closes #662
=> Enhancement 658 661 662

FrontEnd/src/components/AutoQuery/Connected_Component/RobotView.js, FrontEnd/src/components/CommonComponents/RessourcesDisplay/ReactTable/ColumnFilters.js
=> Enhancement 657 655

FrontEnd/src/components/AutoQuery/Connected_Component/TableQuery.js, FrontEnd/src/components/AutoQuery/Connected_Component/TableResultStudy.js, FrontEnd/src/components/AutoQuery/Connected_Component/TableResultsStudiesSeries.js, FrontEnd/src/components/CommonComponents/RessourcesDisplay/ReactTable/ColumnFilters.js, FrontEnd/src/components/CommonComponents/RessourcesDisplay/ReactTable/EditableCells.js
Closing #667 
Closing #668 
Closing #669
Closing #670
Closing #655
=> Fix 667 668

FrontEnd/src/assets/styles/orthancToolsJs.scss, FrontEnd/src/components/AutoQuery/Connected_Component/CustomFilter.js, FrontEnd/src/components/CommonComponents/RessourcesDisplay/ReactTable/ColumnFilters.js
=> Enhancement 673 676

FrontEnd/src/components/Anonymize/AnonHistoric.js, FrontEnd/src/components/AutoQuery/Connected_Component/TableQuery.js, FrontEnd/src/components/CommonComponents/RessourcesDisplay/ReactTable/EditableCells.js
=> Fix 672 674
